version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Imagen de MongoDB
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Usuario para MongoDB
      MONGO_INITDB_ROOT_PASSWORD: adminpassword  # Contraseña para MongoDB
    volumes:
      - mongodb_data:/data/db  # Volumen para persistir datos
      - ./init_data:/docker-entrypoint-initdb.d/
    network_mode: host  # Usa la red del host

volumes:
  mongodb_data:
