version: '3.8'

services:
  mongodb:
    image: mongo:6.0  # Usa una versión estable específica
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"  # Exponiendo MongoDB al puerto local
    volumes:
      - mongodb_data:/data/db  # Volumen para persistencia de datos
    environment:
      MONGO_INITDB_ROOT_USERNAME: adm_user_mongodb  # Usuario root inicial
      MONGO_INITDB_ROOT_PASSWORD: Hg_fdwJjn65Gdsd  # Contraseña del root

  # fastapi:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: fastapi
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./app:/app
  #   depends_on:
  #     - mongodb
  #   networks:
  #     - football_network

volumes:
  mongodb_data:

networks:
  football_network:
    driver: bridge
